### ISSUE TITLE
'retracted' status

### ISSUE THREAD

**Issue by archgogo** [openMetadataInitiative/openMINDS_instances#24]
Datasets that will be removed from EBRAINS KG will get a 'retracted' status. So, there needs to be a openMINDS mechanism in place for this.

**Comment by lzehl** [comment]
@olinux @apdavison can we discuss if this is a term in ProductAccessibility ? If yes, how can this fit in naming wise ? 

We currently have there: 
+ free access
+ controlled access
+ restricted access
+ under embargo

Since we keep the metadata would this then be: 
+ no access ?
+ inaccessible ?
+ unobtainable ?

**Comment by apdavison** [comment]
yes, this fits as a ProductAccessibility term, and I think "retracted" is the most concise and informative term.
